### ISSUE TITLE
Package name

### ISSUE THREAD

**Issue by federicomarini** [csoneson/SEE#1]
I guess we kind of agreed on the name/acronym.
One wild thought on the train home, what if we add an _i_ ahead and make it iSEE - which would go for interactive [SingleCell|Summarized] Experiment Explorer?

**Comment by LTLA** [comment]
That is also cute. Currently it is _SummarizedExplorer_, which pretty much does what it says. 

I also thought about _sexplore_, but the Google search did not end well.

**Comment by federicomarini** [comment]
> I also thought about sexplore, but a routine Google search did not end well.

😄

**Comment by kevinrue** [comment]
I like the `iSEE` idea :)
Also, I agree that `SummarizedExplorer` gives a good hint about what it does, especially if some functions generalise beyond `SingleCellExperiment` objects.

Just to toss my hat into the ring, I was also toying with an acronym on my way back:
"can we do `SCIENCE`"? (we all want to contribute to 'science' ^^)
Single Cell Interactive Explorer for/of N[...], Cluster(ing), and E[...]

**Comment by csoneson** [comment]
I like iSEE! And I agree that it is nice to not limit ourselves to single-cell applications in the name.

**Comment by federicomarini** [comment]
I see we are converging (pun _definitely_ intended).
And yes, @csoneson, I would try to keep the acronym possibly general - even though the core functionality would be dedicated for scRNA-seq applications.

I'll open up a new issue where we can discuss the timeline, it seems quite reasonable we will be aiming for the next release.

**Comment by sballereau** [comment]
Hi,
Good to meet you guys yesterday. iSEE an interactive Summarized Experiment Explorer is a good idea indeed.
Stephane

**Comment by LTLA** [comment]
Closing this, as we seem to have agreed; continue discussion on Slack if necessary.
