### ISSUE TITLE
Slack channel for better/quicker comm?

### ISSUE THREAD

**Issue by federicomarini** [csoneson/SEE#2]
@LTLA what are the requirements for joining the slack channel we mentioned yesterday?
I guess this is a better/quicker way of communicating

Side info: having some nasty compiler and libs issues in switching to Rdevel. I like the development between April and October better 😄

**Comment by kevinrue** [comment]
Can you try this link and let me know what happens?
https://bioc-community.herokuapp.com/
It was the sign-up page in May this year

**Comment by LTLA** [comment]
I think I may have to invite you - which I can, on my other computer that has Slack installed. I'll try to remember to do it tomorrow, nag me if it doesn't happen.

**Comment by kevinrue** [comment]
Separately, I've looked at the `ideal` dashboard and I like the code and organisation a lot, it is super straightforward to read!
If you like, I might be able to spare some time this weekend to extract the backbone of a first panel to get things going (and brush up my Shiny skills) -- I'm all good on the Rdevel side.

@federicomarini : One design question though (until we figure the slack aspect): any particular reason for the single-file application? Or shall we split it up in `ui.R` and `server.R`, as I did for `TVTB::tSVE()` ?

**Comment by federicomarini** [comment]
- slack: I put in my email address and it says "missing scope" on the button - as it did back in may/june

- one file VS ui+server: in this way it is possible to pass the SCE object as parameter(s) in a more explicit way than the runApp-way. Probably it was a cosmetic/pragmatic choice: I liked that as a starter, and it worked. And as for the code structure, thanks 😊

**Comment by csoneson** [comment]
@kevinrue / @LTLA : would one of you be able to invite me to the Slack channel as well? 

Regarding one file/ui+server: I have also come to like having everything in one file, I used the same approach as Federico in our [iCOBRA](https://github.com/markrobinsonuzh/iCOBRA/blob/master/R/shiny.R) app. 

@kevinrue : if you have some time to make a first backbone, that would be great. BTW, related to our discussion, I have to read up a bit on [shiny modules](https://shiny.rstudio.com/articles/modules.html), but it may be something we want to keep in mind

**Comment by kevinrue** [comment]
@csoneson , you should have the invitation email now.

@federicomarini : yes, a sub-channel is the best way to proceed. I've just created one and invited @LTLA and @federicomarini until @csoneson joins the slack community.

I'll just list a few thoughts here, each of which should probably warrant a separate issue if anyone wishes to discuss them:

1)
@csoneson : I was super interested in Shiny module at the time I was developing `TVTB`, but they were still recent features, not very well documented or supported (cf. “Just use functions!” historical reply in the link that you sent). From a quick look, they seem to have matured well, reviving my interest! 
A somewhat related idea that hit me during Simon Anders's mention of [linked charts](https://github.com/anders-biostat/linked-charts) and `hwriter::hwrite()` [link](https://cran.r-project.org/web/packages/hwriter/hwriter.pdf) would be an HTML representation of S4 objects (_e.g._ a `show_html(object)` generic and/or smaller modules such as `shiny_assay()`,`shiny_colData()` that would offer a frequently used interface to select/peak into individual slots of an object that inherits from `SummarizedExperiment`).

2)
regarding the point made in #1 that A) we'd like to supports both `SummarizedExperiment` and `SingleCellExperiment`, and B) we'd like to make use of pre-computed data such as dimensionality reduction coordinates, it occurred to me that `SummarizedExperiment` does not have a `reduceDims` slot to store/access those precomputed results. I thought I'd get the ball rolling just to think about handling this situation. Among the ideas that I brainstormed: should/can we implement a `setAs` method that turn a `SE` (for short) into an `SCE` for use internally in the app?

3)
I'm 100% for the single-file app based on a quick code review and the discussion.
Just for the sake of having a comparison written out somewhere, in `TVTB::tSVE()` [here](https://github.com/kevinrue/TVTB/search?utf8=✓&q=.tSVE&type=) I resorted to an environment-mediated strategy to pass objects from the workspace to populate the defaults settings of the app.
One benefit is that it 'scopes away' those object names from the internal app ones. But that is generally not a problem, as multiple reactiveValues() can be used to 'scope' groups of reactive values to avoid this type of clash (modules can do that too).

**Comment by LTLA** [comment]
Regarding point 2, we already have that:

```r
library(SingleCellExperiment)
library(scRNAseq)
data(allen)
sce <- as(allen, "SingleCellExperiment")
```

**Comment by federicomarini** [comment]
Sparse thoughts on the mentioned points:

1 - I am not familiar with modules either as of now. It can become something for version 2.0 maybe? Just saying, since we plan to strip down the backbone, I would not try to complicate things from the start 😃 

2 - as Aaron said, the coercion possibility is somehow already in place. And maybe it would be a thought worth throwing to the core team to put the reducedDims slot also for the simple SummarizedExperiment?

That being said, I seem to have resolved the issue with devel - if you want to, you don't have to do the bootstrap and I can soon dedicate some time to get the "true" v.0.98.1

**Comment by LTLA** [comment]
Let's move this discussion to Slack.
